package com.prishtha.mvp.identity.internal.enums;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    LOGOUT,
    TOKEN_REFRESH,
    SOCIAL_LOGIN_GOOGLE,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHALLENGE_ISSUED,
    MFA_SUCCESS,
    MFA_FAILURE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    SESSION_REVOKED,
    ALL_SESSIONS_REVOKED
}
